DROP TABLE IF EXISTS participation_request CASCADE;
DROP TABLE IF EXISTS ref_event_compilation CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

COMMENT ON TABLE category IS 'Категории';
COMMENT ON COLUMN category.id IS 'Уникальный идентификатор категории';
COMMENT ON COLUMN category.name IS 'Название категории. Уникальное значение (от 1 до 50 символов)';

CREATE TABLE IF NOT EXISTS "user"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    name  VARCHAR(250)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

COMMENT ON TABLE "user" IS 'Пользователи системы';
COMMENT ON COLUMN "user".id IS 'Уникальный идентификатор пользователя';
COMMENT ON COLUMN "user".email IS 'Электронная почта пользователя (уникальный email, от 6 до 254 символов)';
COMMENT ON COLUMN "user".name IS 'Имя или логин пользователя (от 2 до 250 символов)';

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT REFERENCES category (id) ON DELETE RESTRICT,
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    lat                FLOAT                                   NOT NULL,
    lon                FLOAT                                   NOT NULL,
    paid               BOOLEAN                                 NOT NULL DEFAULT FALSE,
    participant_limit  INTEGER                                 NOT NULL DEFAULT 0,
    request_moderation BOOLEAN                                          DEFAULT TRUE,
    title              VARCHAR(120)                            NOT NULL,
    state_action       VARCHAR(120)                            NOT NULL DEFAULT 'SEND_TO_REVIEW',
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    state              VARCHAR(120)                                     DEFAULT 'PENDING',
    initiator_id       BIGINT REFERENCES "user" (id) ON DELETE RESTRICT,
    CONSTRAINT chk_event_state_action CHECK (state_action IN ('SEND_TO_REVIEW', 'CANCEL_REVIEW', 'PUBLISH_EVENT', 'REJECT_EVENT')),
    CONSTRAINT chk_event_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

COMMENT ON TABLE event IS 'События, создаваемые пользователями и модерируемые администратором';
COMMENT ON COLUMN event.id IS 'Уникальный идентификатор события';
COMMENT ON COLUMN event.annotation IS 'Краткое описание события (от 20 до 2000 символов)';
COMMENT ON COLUMN event.category_id IS 'Идентификатор категории, к которой относится событие';
COMMENT ON COLUMN event.description IS 'Полное описание события (от 20 до 7000 символов)';
COMMENT ON COLUMN event.event_date IS 'Дата и время, на которые намечено событие (не может быть в прошлом)';
COMMENT ON COLUMN event.lat IS 'Широта локации проведения события';
COMMENT ON COLUMN event.lon IS 'Долгота локации проведения события';
COMMENT ON COLUMN event.paid IS 'Флаг оплаты участия: true — платное, false — бесплатное';
COMMENT ON COLUMN event.participant_limit IS 'Ограничение на количество участников. 0 — отсутствие ограничения';
COMMENT ON COLUMN event.request_moderation IS 'Нужна ли пре-модерация заявок: true — подтверждает инициатор, false — автоматически';
COMMENT ON COLUMN event.title IS 'Заголовок события (от 3 до 120 символов)';
COMMENT ON COLUMN event.state_action IS 'Enum: Действие над изменением статуса события. Возможные значения для пользователя: SEND_TO_REVIEW, CANCEL_REVIEW. Для администратора: PUBLISH_EVENT, REJECT_EVENT';
COMMENT ON COLUMN event.created_on IS 'Дата и время создания события (автоматически при сохранении)';
COMMENT ON COLUMN event.published_on IS 'Дата и время публикации события администратором';
COMMENT ON COLUMN event.state IS 'Enum: Статус жизненного цикла события. Возможные значения: PENDING (ожидает модерации), PUBLISHED (опубликовано), CANCELED (отменено)';
COMMENT ON COLUMN event.initiator_id IS 'Идентификатор пользователя, который является организатором (инициатором) события';

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL DEFAULT FALSE,
    title  VARCHAR(120)                            NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

COMMENT ON TABLE compilation IS 'Подборки событий, формируемые администратором';
COMMENT ON COLUMN compilation.id IS 'Уникальный идентификатор подборки';
COMMENT ON COLUMN compilation.pinned IS 'Закреплена ли подборка на главной странице сайта (true/false)';
COMMENT ON COLUMN compilation.title IS 'Заголовок подборки событий (от 1 до 120 символов)';

CREATE TABLE IF NOT EXISTS ref_event_compilation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id BIGINT REFERENCES compilation (id) ON DELETE CASCADE,
    event_id       BIGINT REFERENCES event (id) ON DELETE CASCADE,
    CONSTRAINT pk_ref_event_compilation PRIMARY KEY (id),
    CONSTRAINT unique_event_compilation UNIQUE (compilation_id, event_id)
);

COMMENT ON TABLE ref_event_compilation IS 'Таблица связи Many-to-Many между подборками и включенными в них событиями';
COMMENT ON COLUMN ref_event_compilation.compilation_id IS 'Идентификатор подборки событий';
COMMENT ON COLUMN ref_event_compilation.event_id IS 'Идентификатор события, включенного в подборку';

CREATE TABLE IF NOT EXISTS participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT REFERENCES event (id) ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    requester_id BIGINT REFERENCES "user" (id) ON DELETE RESTRICT,
    status       VARCHAR(120)                            NOT NULL DEFAULT 'PENDING',
    CONSTRAINT chk_participation_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    CONSTRAINT unique_participation_request UNIQUE (event_id, requester_id),
    CONSTRAINT pk_participation_request PRIMARY KEY (id)
);

COMMENT ON TABLE participation_request IS 'Заявки пользователей на участие в событиях';
COMMENT ON COLUMN participation_request.id IS 'Уникальный идентификатор заявки';
COMMENT ON COLUMN participation_request.event_id IS 'Идентификатор события, на участие в котором подана заявка';
COMMENT ON COLUMN participation_request.created IS 'Дата и время создания заявки';
COMMENT ON COLUMN participation_request.requester_id IS 'Идентификатор пользователя, отправившего запрос на участие';
COMMENT ON COLUMN participation_request.status IS 'Enum: Статус заявки на участие. Возможные значения: PENDING (ожидает рассмотрения), CONFIRMED (подтверждена), REJECTED (отклонена), CANCELED (отменена самим пользователем)';
